version: 2

models:
  - name: customers
    description: '{{ doc("coffee_shop") }}'
    columns:
      - name: customer_id
        description: Primary key of the model
        tests:
           - unique
           - not_null
      - name: name
      - name: email
      - name: n_orders
      - name: first_order_at

  - name: monthly_customers
    description: '{{ doc("coffee_shop") }}'
    columns:
      - name: date_month
      - name: new_customers

sources:
  - name: coffee_shop
    project: coffee_shop
    freshness:
      error_after:
        count: 12
        period: hour
    loaded_at_field: created_at